# Generated by Django 4.2.11 on 2024-03-23 18:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IHA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=225)),
                ('brand', models.CharField(max_length=40)),
                ('serial_number', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('engine', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('mileage', models.DecimalField(decimal_places=0, max_digits=6)),
                ('location', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('used', 'used'), ('new', 'new')], max_length=50)),
                ('day_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='IHAPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('iha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ihas.iha')),
            ],
        ),
    ]
